apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskflow-redis-data
  namespace: taskflow-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
